### ISSUE TITLE
En tant qu'utilisateur je veux aller sur la page d'accueil afin de lire la présentation de la ville

### ISSUE THREAD

**Issue by jochy** [jochy/MA-Guide#1]

**Comment by jochy** [comment]
Test d'acceptance : 

Etant donné : 
 - la page d’accueil contenant la description de la ville
 - un utilisateur 
Quand : 
 - l'utilisateur clique sur le bouton "Accueil"
Alors : 
 - la page d'accueil s'affiche avec la description de la ville

**Comment by jochy** [comment]
Effort : 1 (juste image + texte sur un template fourni)

**Comment by Edsolat** [comment]
Page d'accueil --> index.html : présentation rapide de la ville
