### ISSUE TITLE
En tant qu'utilisateur, je veux consulter la liste des hôtels afin de me renseigner sur les différents hôtels disponibles

### ISSUE THREAD

**Issue by jochy** [jochy/MA-Guide#2]

**Comment by jochy** [comment]
Test d'acceptance : 

Etant donné : 
 - la page d'accueil contenant un bouton pour aller sur la page des hôtels
 - un utilisateur
Quand : 
 - l'utilisateur clique sur le bouton "Liste des hôtels"
Alors : 
 - La page des différents hôtels apparaît


Etant donné : 
 - la page d'accueil contenant un lien vers la page des hôtels dans une de ses rubriques 
 - un utilisateur
Quand : 
 - L'utilisateur clique sur le lien
Alors : 
 - La page des différents hôtels apparaît


Etant donné : 
 - la page des hôtels avec un hôtel proposé
 - un utilisateur
Quand : 
 - l'utilisateur clique sur l'hôtel
Alors : 
 - il est redirigé vers le site de l'hotel

**Comment by jochy** [comment]
Effort : 3

**Comment by Edsolat** [comment]
hotels.html + hotelsx.html (x = 2 à 5) --> liste des hotels (avec filtre par étoiles)
